CREATE USER farmaciamia IDENTIFIED BY mia12far
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;

GRANT DBA TO farmaciamia;
GRANT CONNECT, RESOURCE TO farmaciamia;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM TO farmaciamia;
GRANT UNLIMITED TABLESPACE TO farmaciamia;
