CREATE TABLE SUCURSAL (
  COD_SUCURSAL  NUMBER(3)      NOT NULL,
  NOMBRE        VARCHAR2(50)   NOT NULL,
  CIUDAD        VARCHAR2(50)   NOT NULL,
  DIRECCION     VARCHAR2(100),
  TELEFONO      VARCHAR2(15),
  CONSTRAINT PK_SUCURSAL PRIMARY KEY (COD_SUCURSAL)
);

CREATE TABLE CATEGORIA (
  COD_CATEGORIA NUMBER(3)      NOT NULL,
  NOMBRE        VARCHAR2(50)   NOT NULL,
  DESCRIPCION   VARCHAR2(150),
  CONSTRAINT PK_CATEGORIA PRIMARY KEY (COD_CATEGORIA)
);

CREATE TABLE PROVEEDOR (
  RUC_PROVEEDOR VARCHAR2(13)   NOT NULL,
  NOMBRE        VARCHAR2(100)  NOT NULL,
  TELEFONO      VARCHAR2(15),
  EMAIL         VARCHAR2(100),
  DIRECCION     VARCHAR2(150),
  CONSTRAINT PK_PROVEEDOR PRIMARY KEY (RUC_PROVEEDOR)
);

CREATE TABLE PRODUCTO (
  COD_PRODUCTO    NUMBER(6)     NOT NULL,
  NOMBRE          VARCHAR2(100) NOT NULL,
  DESCRIPCION     VARCHAR2(200),
  PRECIO          NUMBER(10,2)  NOT NULL,
  REQUIERE_RECETA CHAR(1)       DEFAULT 'N' NOT NULL,
  COD_CATEGORIA   NUMBER(3)     NOT NULL,
  RUC_PROVEEDOR   VARCHAR2(13)  NOT NULL,
  CONSTRAINT PK_PRODUCTO PRIMARY KEY (COD_PRODUCTO),
  CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA (COD_CATEGORIA),
  CONSTRAINT FK_PRODUCTO_PROVEEDOR FOREIGN KEY (RUC_PROVEEDOR) REFERENCES PROVEEDOR (RUC_PROVEEDOR),
  CONSTRAINT CK_PRODUCTO_RECETA CHECK (REQUIERE_RECETA IN ('S','N'))
);

CREATE TABLE INVENTARIO (
  COD_INVENTARIO NUMBER(10)    NOT NULL,
  COD_PRODUCTO   NUMBER(6)     NOT NULL,
  COD_SUCURSAL   NUMBER(3)     NOT NULL,
  STOCK          NUMBER(8)     DEFAULT 0 NOT NULL,
  STOCK_MIN      NUMBER(8)     DEFAULT 0 NOT NULL,
  STOCK_MAX      NUMBER(8),
  CONSTRAINT PK_INVENTARIO PRIMARY KEY (COD_INVENTARIO),
  CONSTRAINT FK_INVENTARIO_PRODUCTO FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO (COD_PRODUCTO),
  CONSTRAINT FK_INVENTARIO_SUCURSAL FOREIGN KEY (COD_SUCURSAL) REFERENCES SUCURSAL (COD_SUCURSAL),
  CONSTRAINT UQ_INVENTARIO_PROD_SUC UNIQUE (COD_PRODUCTO, COD_SUCURSAL),
  CONSTRAINT CK_INVENTARIO_STOCK CHECK (STOCK >= 0)
);

CREATE SEQUENCE SEQ_SUCURSAL   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORIA  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUCTO   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INVENTARIO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE EMPLEADO (
  CED_EMPLEADO  VARCHAR2(10)  NOT NULL,
  NOMBRES       VARCHAR2(60)  NOT NULL,
  APELLIDOS     VARCHAR2(60)  NOT NULL,
  CARGO         VARCHAR2(40)  NOT NULL,
  TELEFONO      VARCHAR2(15),
  COD_SUCURSAL  NUMBER(3)     NOT NULL,
  CONSTRAINT PK_EMPLEADO PRIMARY KEY (CED_EMPLEADO),
  CONSTRAINT FK_EMPLEADO_SUCURSAL FOREIGN KEY (COD_SUCURSAL) REFERENCES SUCURSAL (COD_SUCURSAL)
);

CREATE TABLE CLIENTE (
  CED_CLIENTE   VARCHAR2(10)  NOT NULL,
  NOMBRES       VARCHAR2(60)  NOT NULL,
  APELLIDOS     VARCHAR2(60)  NOT NULL,
  TELEFONO      VARCHAR2(15),
  EMAIL         VARCHAR2(100),
  DIRECCION     VARCHAR2(150),
  CONSTRAINT PK_CLIENTE PRIMARY KEY (CED_CLIENTE)
);

CREATE TABLE VENTA (
  NUM_VENTA     NUMBER(10)    NOT NULL,
  FECHA         DATE          DEFAULT SYSDATE NOT NULL,
  CED_CLIENTE   VARCHAR2(10),
  CED_EMPLEADO  VARCHAR2(10)  NOT NULL,
  COD_SUCURSAL  NUMBER(3)     NOT NULL,
  CONSTRAINT PK_VENTA PRIMARY KEY (NUM_VENTA),
  CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (CED_CLIENTE) REFERENCES CLIENTE (CED_CLIENTE),
  CONSTRAINT FK_VENTA_EMPLEADO FOREIGN KEY (CED_EMPLEADO) REFERENCES EMPLEADO (CED_EMPLEADO),
  CONSTRAINT FK_VENTA_SUCURSAL FOREIGN KEY (COD_SUCURSAL) REFERENCES SUCURSAL (COD_SUCURSAL)
);

CREATE TABLE DETALLE_VENTA (
  NUM_VENTA      NUMBER(10)    NOT NULL,
  COD_PRODUCTO   NUMBER(6)     NOT NULL,
  CANTIDAD       NUMBER(6)     NOT NULL,
  PRECIO_UNIT    NUMBER(10,2)  NOT NULL,
  CONSTRAINT PK_DETALLE_VENTA PRIMARY KEY (NUM_VENTA, COD_PRODUCTO),
  CONSTRAINT FK_DETVENTA_VENTA FOREIGN KEY (NUM_VENTA) REFERENCES VENTA (NUM_VENTA),
  CONSTRAINT FK_DETVENTA_PRODUCTO FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO (COD_PRODUCTO),
  CONSTRAINT CK_DETVENTA_CANTIDAD CHECK (CANTIDAD > 0),
  CONSTRAINT CK_DETVENTA_PRECIO CHECK (PRECIO_UNIT >= 0)
);

CREATE SEQUENCE SEQ_VENTA START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE COMPRA (
  NUM_COMPRA    NUMBER(10)    NOT NULL,
  FECHA         DATE          DEFAULT SYSDATE NOT NULL,
  ESTADO        VARCHAR2(15)  DEFAULT 'PENDIENTE' NOT NULL,
  RUC_PROVEEDOR VARCHAR2(13)  NOT NULL,
  COD_SUCURSAL  NUMBER(3)     NOT NULL,
  CONSTRAINT PK_COMPRA PRIMARY KEY (NUM_COMPRA),
  CONSTRAINT FK_COMPRA_PROVEEDOR FOREIGN KEY (RUC_PROVEEDOR) REFERENCES PROVEEDOR (RUC_PROVEEDOR),
  CONSTRAINT FK_COMPRA_SUCURSAL FOREIGN KEY (COD_SUCURSAL) REFERENCES SUCURSAL (COD_SUCURSAL),
  CONSTRAINT CK_COMPRA_ESTADO CHECK (ESTADO IN ('PENDIENTE','RECIBIDA','ANULADA'))
);

CREATE TABLE DETALLE_COMPRA (
  NUM_COMPRA     NUMBER(10)    NOT NULL,
  COD_PRODUCTO   NUMBER(6)     NOT NULL,
  CANTIDAD       NUMBER(6)     NOT NULL,
  PRECIO_COMPRA  NUMBER(10,2)  NOT NULL,
  CONSTRAINT PK_DETALLE_COMPRA PRIMARY KEY (NUM_COMPRA, COD_PRODUCTO),
  CONSTRAINT FK_DETCOMPRA_COMPRA FOREIGN KEY (NUM_COMPRA) REFERENCES COMPRA (NUM_COMPRA),
  CONSTRAINT FK_DETCOMPRA_PRODUCTO FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO (COD_PRODUCTO),
  CONSTRAINT CK_DETCOMPRA_CANTIDAD CHECK (CANTIDAD > 0),
  CONSTRAINT CK_DETCOMPRA_PRECIO CHECK (PRECIO_COMPRA >= 0)
);

CREATE SEQUENCE SEQ_COMPRA START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- INDICES
-- ============================================================

-- IX_PRODUCTO_CATEGORIA: acelera el JOIN PRODUCTO-CATEGORIA y la validacion
-- de la FK al insertar o actualizar productos.
CREATE INDEX IX_PRODUCTO_CATEGORIA ON PRODUCTO (COD_CATEGORIA);

-- IX_PRODUCTO_PROVEEDOR: acelera el JOIN PRODUCTO-PROVEEDOR y las consultas
-- de "productos por proveedor" para planificar compras.
CREATE INDEX IX_PRODUCTO_PROVEEDOR ON PRODUCTO (RUC_PROVEEDOR);

-- IX_INVENTARIO_PRODUCTO: acelera las consultas de stock por producto y la
-- validacion de la FK de COD_PRODUCTO.
CREATE INDEX IX_INVENTARIO_PRODUCTO ON INVENTARIO (COD_PRODUCTO);

-- IX_INVENTARIO_SUCURSAL: acelera el reporte de inventario por sucursal y la
-- validacion de la FK de COD_SUCURSAL.
CREATE INDEX IX_INVENTARIO_SUCURSAL ON INVENTARIO (COD_SUCURSAL);

-- IX_EMPLEADO_SUCURSAL: acelera listar empleados por sucursal y la FK.
CREATE INDEX IX_EMPLEADO_SUCURSAL ON EMPLEADO (COD_SUCURSAL);

-- IX_VENTA_CLIENTE: acelera el historial de compras por cliente y la FK.
CREATE INDEX IX_VENTA_CLIENTE ON VENTA (CED_CLIENTE);

-- IX_VENTA_EMPLEADO: acelera las ventas por vendedor y la FK.
CREATE INDEX IX_VENTA_EMPLEADO ON VENTA (CED_EMPLEADO);

-- IX_VENTA_SUC_FECHA: indice COMPUESTO. Acelera el reporte de ventas por
-- sucursal y rango de fechas (RF-12) y ademas cubre la FK de COD_SUCURSAL,
-- por lo que no se crea un indice simple aparte para esa FK.
CREATE INDEX IX_VENTA_SUC_FECHA ON VENTA (COD_SUCURSAL, FECHA);

-- IX_DETVENTA_PRODUCTO: acelera la FK y el reporte de productos mas vendidos.
-- (NUM_VENTA ya esta indexado por la PK compuesta, no se duplica.)
CREATE INDEX IX_DETVENTA_PRODUCTO ON DETALLE_VENTA (COD_PRODUCTO);

-- IX_COMPRA_PROVEEDOR: acelera las compras por proveedor y la FK.
CREATE INDEX IX_COMPRA_PROVEEDOR ON COMPRA (RUC_PROVEEDOR);

-- IX_COMPRA_SUCURSAL: acelera las compras por sucursal y la FK.
CREATE INDEX IX_COMPRA_SUCURSAL ON COMPRA (COD_SUCURSAL);

-- IX_DETCOMPRA_PRODUCTO: acelera la FK y el analisis de costo por producto.
-- (NUM_COMPRA ya esta indexado por la PK compuesta, no se duplica.)
CREATE INDEX IX_DETCOMPRA_PRODUCTO ON DETALLE_COMPRA (COD_PRODUCTO);

-- IX_PRODUCTO_NOMBRE: indice SIMPLE. Acelera la busqueda de productos por
-- nombre en el punto de venta (cajero en hora pico).
CREATE INDEX IX_PRODUCTO_NOMBRE ON PRODUCTO (NOMBRE);
