CREATE USER farmaciamia_sucursal IDENTIFIED BY suc12mia
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE TO farmaciamia_sucursal;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM,
      CREATE MATERIALIZED VIEW TO farmaciamia_sucursal;
GRANT UNLIMITED TABLESPACE TO farmaciamia_sucursal;

CREATE TABLE farmaciamia_sucursal.INVENTARIO (
  COD_INVENTARIO NUMBER(10)   NOT NULL,
  COD_PRODUCTO   NUMBER(6)    NOT NULL,
  COD_SUCURSAL   NUMBER(3)    NOT NULL,
  STOCK          NUMBER(8)    DEFAULT 0 NOT NULL,
  STOCK_MIN      NUMBER(8)    DEFAULT 0 NOT NULL,
  STOCK_MAX      NUMBER(8),
  CONSTRAINT PK_SUC_INVENTARIO PRIMARY KEY (COD_INVENTARIO),
  CONSTRAINT UQ_SUC_INV_PROD UNIQUE (COD_PRODUCTO, COD_SUCURSAL),
  CONSTRAINT CK_SUC_INV_STOCK CHECK (STOCK >= 0)
);

CREATE TABLE farmaciamia_sucursal.VENTA (
  NUM_VENTA     NUMBER(10)    NOT NULL,
  FECHA         DATE          DEFAULT SYSDATE NOT NULL,
  CED_CLIENTE   VARCHAR2(10),
  CED_EMPLEADO  VARCHAR2(10)  NOT NULL,
  COD_SUCURSAL  NUMBER(3)     NOT NULL,
  CONSTRAINT PK_SUC_VENTA PRIMARY KEY (NUM_VENTA)
);

CREATE TABLE farmaciamia_sucursal.DETALLE_VENTA (
  NUM_VENTA     NUMBER(10)    NOT NULL,
  COD_PRODUCTO  NUMBER(6)     NOT NULL,
  CANTIDAD      NUMBER(6)     NOT NULL,
  PRECIO_UNIT   NUMBER(10,2)  NOT NULL,
  CONSTRAINT PK_SUC_DETVENTA PRIMARY KEY (NUM_VENTA, COD_PRODUCTO),
  CONSTRAINT FK_SUC_DETVENTA_VENTA FOREIGN KEY (NUM_VENTA) REFERENCES farmaciamia_sucursal.VENTA (NUM_VENTA),
  CONSTRAINT CK_SUC_DETVENTA_CANT CHECK (CANTIDAD > 0)
);

INSERT INTO farmaciamia_sucursal.INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (1, 1, 2, 40, 10, 200);
INSERT INTO farmaciamia_sucursal.INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (2, 2, 2, 15, 10, 150);
INSERT INTO farmaciamia_sucursal.INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (3, 3, 2, 3, 15, 100);
INSERT INTO farmaciamia_sucursal.INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (4, 4, 2, 60, 5, 80);
INSERT INTO farmaciamia_sucursal.INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (5, 5, 2, 20, 10, 120);

INSERT INTO farmaciamia_sucursal.VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (101, DATE '2026-09-06', NULL, '1400112044', 2);
INSERT INTO farmaciamia_sucursal.VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (102, DATE '2026-09-07', NULL, '1400112055', 2);
INSERT INTO farmaciamia_sucursal.VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (103, DATE '2026-09-08', NULL, '1400112044', 2);
INSERT INTO farmaciamia_sucursal.VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (104, DATE '2026-09-09', NULL, '1400112066', 2);
INSERT INTO farmaciamia_sucursal.VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (105, DATE '2026-09-10', NULL, '1400112077', 2);

INSERT INTO farmaciamia_sucursal.DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (101, 1, 3, 1.50);
INSERT INTO farmaciamia_sucursal.DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (102, 2, 2, 3.75);
INSERT INTO farmaciamia_sucursal.DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (103, 3, 1, 5.20);
INSERT INTO farmaciamia_sucursal.DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (104, 4, 2, 8.90);
INSERT INTO farmaciamia_sucursal.DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (105, 5, 4, 4.30);

COMMIT;

GRANT SELECT ON farmaciamia_sucursal.INVENTARIO    TO farmaciamia;
GRANT SELECT ON farmaciamia_sucursal.VENTA         TO farmaciamia;
GRANT SELECT ON farmaciamia_sucursal.DETALLE_VENTA TO farmaciamia;
GRANT SELECT ON farmaciamia.PRODUCTO   TO farmaciamia_sucursal;
GRANT SELECT ON farmaciamia.SUCURSAL   TO farmaciamia_sucursal;
GRANT SELECT ON farmaciamia.INVENTARIO TO farmaciamia_sucursal;
GRANT SELECT ON farmaciamia.VENTA      TO farmaciamia_sucursal;

CREATE OR REPLACE VIEW farmaciamia.VW_INVENTARIO_GLOBAL AS
SELECT 'MATRIZ' AS ORIGEN, i.COD_SUCURSAL, p.COD_PRODUCTO, p.NOMBRE AS PRODUCTO,
       i.STOCK, i.STOCK_MIN,
       CASE WHEN i.STOCK <= i.STOCK_MIN THEN 'ALERTA' ELSE 'OK' END AS ESTADO_STOCK
FROM farmaciamia.INVENTARIO i
JOIN farmaciamia.PRODUCTO p ON p.COD_PRODUCTO = i.COD_PRODUCTO
UNION ALL
SELECT 'SUCURSAL', i.COD_SUCURSAL, p.COD_PRODUCTO, p.NOMBRE,
       i.STOCK, i.STOCK_MIN,
       CASE WHEN i.STOCK <= i.STOCK_MIN THEN 'ALERTA' ELSE 'OK' END
FROM farmaciamia_sucursal.INVENTARIO i
JOIN farmaciamia.PRODUCTO p ON p.COD_PRODUCTO = i.COD_PRODUCTO;

CREATE MATERIALIZED VIEW farmaciamia.MV_VENTAS_GLOBALES
  TABLESPACE USERS
  BUILD IMMEDIATE
  REFRESH COMPLETE ON DEMAND
AS
SELECT 'MATRIZ' AS ORIGEN, v.NUM_VENTA, v.FECHA, v.COD_SUCURSAL,
       d.COD_PRODUCTO, d.CANTIDAD, d.PRECIO_UNIT,
       d.CANTIDAD * d.PRECIO_UNIT AS SUBTOTAL
FROM farmaciamia.VENTA v
JOIN farmaciamia.DETALLE_VENTA d ON d.NUM_VENTA = v.NUM_VENTA
UNION ALL
SELECT 'SUCURSAL', v.NUM_VENTA, v.FECHA, v.COD_SUCURSAL,
       d.COD_PRODUCTO, d.CANTIDAD, d.PRECIO_UNIT,
       d.CANTIDAD * d.PRECIO_UNIT
FROM farmaciamia_sucursal.VENTA v
JOIN farmaciamia_sucursal.DETALLE_VENTA d ON d.NUM_VENTA = v.NUM_VENTA;

BEGIN
  DBMS_SCHEDULER.CREATE_JOB (
    job_name        => 'JOB_MV_VENTAS_DIARIO',
    job_type        => 'PLSQL_BLOCK',
    job_action      => 'BEGIN DBMS_MVIEW.REFRESH(''FARMACIAMIA.MV_VENTAS_GLOBALES'', ''C''); END;',
    start_date      => TRUNC(SYSDATE) + 1 + 1/24,
    repeat_interval => 'FREQ=DAILY;BYHOUR=1;BYMINUTE=0;BYSECOND=0',
    enabled         => TRUE);
END;
/

CREATE OR REPLACE PROCEDURE farmaciamia.PR_VENTA_PRODUCTO (
  p_cod_producto IN NUMBER,
  p_cod_sucursal IN NUMBER,
  p_cantidad     IN NUMBER,
  p_ced_empleado IN VARCHAR2,
  p_ced_cliente  IN VARCHAR2 DEFAULT NULL
) AS
  v_precio NUMBER(10,2);
  v_stock  NUMBER(8);
  v_venta  NUMBER(10);
BEGIN
  SELECT PRECIO INTO v_precio
    FROM farmaciamia.PRODUCTO
   WHERE COD_PRODUCTO = p_cod_producto;
  SELECT STOCK INTO v_stock
    FROM farmaciamia.INVENTARIO
   WHERE COD_PRODUCTO = p_cod_producto AND COD_SUCURSAL = p_cod_sucursal;
  IF v_stock < p_cantidad THEN
    RAISE_APPLICATION_ERROR(-20001, 'Stock insuficiente para el producto ' || p_cod_producto);
  END IF;
  SELECT NVL(MAX(NUM_VENTA), 0) + 1 INTO v_venta FROM farmaciamia.VENTA;
  INSERT INTO farmaciamia.VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL)
  VALUES (v_venta, SYSDATE, p_ced_cliente, p_ced_empleado, p_cod_sucursal);
  INSERT INTO farmaciamia.DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT)
  VALUES (v_venta, p_cod_producto, p_cantidad, v_precio);
  UPDATE farmaciamia.INVENTARIO
     SET STOCK = STOCK - p_cantidad
   WHERE COD_PRODUCTO = p_cod_producto AND COD_SUCURSAL = p_cod_sucursal;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Venta ' || v_venta || ' registrada. Stock restante: ' || (v_stock - p_cantidad));
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20002, 'Producto o inventario no encontrado');
END;
/

CREATE OR REPLACE PROCEDURE farmaciamia.PR_ACTUALIZAR_STOCK (
  p_cod_producto IN NUMBER,
  p_cod_sucursal IN NUMBER,
  p_nuevo_stock  IN NUMBER
) AS
  v_id NUMBER(10);
BEGIN
  IF p_nuevo_stock < 0 THEN
    RAISE_APPLICATION_ERROR(-20003, 'El stock no puede ser negativo');
  END IF;
  UPDATE farmaciamia.INVENTARIO
     SET STOCK = p_nuevo_stock
   WHERE COD_PRODUCTO = p_cod_producto AND COD_SUCURSAL = p_cod_sucursal;
  IF SQL%ROWCOUNT = 0 THEN
    SELECT NVL(MAX(COD_INVENTARIO), 0) + 1 INTO v_id FROM farmaciamia.INVENTARIO;
    INSERT INTO farmaciamia.INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN)
    VALUES (v_id, p_cod_producto, p_cod_sucursal, p_nuevo_stock, 0);
  END IF;
  COMMIT;
END;
/

CREATE OR REPLACE FUNCTION farmaciamia.FN_TOTAL_VENTA (p_num_venta IN NUMBER)
RETURN NUMBER AS
  v_total NUMBER(12,2);
BEGIN
  SELECT NVL(SUM(CANTIDAD * PRECIO_UNIT), 0) INTO v_total
    FROM farmaciamia.DETALLE_VENTA
   WHERE NUM_VENTA = p_num_venta;
  RETURN v_total;
END;
/

CREATE OR REPLACE FUNCTION farmaciamia.FN_STOCK_GLOBAL (p_cod_producto IN NUMBER)
RETURN NUMBER AS
  v_total NUMBER(10);
BEGIN
  SELECT (SELECT NVL(SUM(STOCK), 0) FROM farmaciamia.INVENTARIO WHERE COD_PRODUCTO = p_cod_producto)
       + (SELECT NVL(SUM(STOCK), 0) FROM farmaciamia_sucursal.INVENTARIO WHERE COD_PRODUCTO = p_cod_producto)
    INTO v_total
    FROM DUAL;
  RETURN v_total;
END;
/

SELECT * FROM farmaciamia.VW_INVENTARIO_GLOBAL;
SELECT * FROM farmaciamia.MV_VENTAS_GLOBALES;
SELECT farmaciamia.FN_TOTAL_VENTA(1) AS TOTAL_VENTA_1 FROM DUAL;
SELECT farmaciamia.FN_STOCK_GLOBAL(1) AS STOCK_GLOBAL_PROD_1 FROM DUAL;
