SET DEFINE OFF
SET SERVEROUTPUT ON

BEGIN
  FOR r IN (SELECT sid, serial# FROM v$session
             WHERE username IN ('FARMACIAMIA','FARMACIAMIA_SUCURSAL','FARMACIAMIA_REPLICA',
                                'U_CONSULTA','U_VENTAS','U_ALMACEN')) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || r.sid || ',' || r.serial# || ''' IMMEDIATE';
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END LOOP;
  DBMS_SESSION.SLEEP(3);
END;
/

BEGIN EXECUTE IMMEDIATE 'DROP USER u_consulta CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER u_ventas CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER u_almacen CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER farmaciamia_replica CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER farmaciamia_sucursal CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER farmaciamia CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ROL_CONSULTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ROL_VENTAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ROL_ALMACEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_SCHEDULER.DROP_JOB('JOB_MV_VENTAS_DIARIO', TRUE); EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE USER farmaciamia IDENTIFIED BY mia12far
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;
GRANT DBA TO farmaciamia;
GRANT CONNECT, RESOURCE TO farmaciamia;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM TO farmaciamia;
GRANT UNLIMITED TABLESPACE TO farmaciamia;

ALTER SESSION SET CURRENT_SCHEMA = farmaciamia;



CREATE TABLE SUCURSAL (
  COD_SUCURSAL  NUMBER(3)      NOT NULL,
  NOMBRE        VARCHAR2(50)   NOT NULL,
  CIUDAD        VARCHAR2(50)   NOT NULL,
  DIRECCION     VARCHAR2(100),
  TELEFONO      VARCHAR2(15),
  CONSTRAINT PK_SUCURSAL PRIMARY KEY (COD_SUCURSAL)
);

CREATE TABLE CATEGORIA (
  COD_CATEGORIA NUMBER(3)      NOT NULL,
  NOMBRE        VARCHAR2(50)   NOT NULL,
  DESCRIPCION   VARCHAR2(150),
  CONSTRAINT PK_CATEGORIA PRIMARY KEY (COD_CATEGORIA)
);

CREATE TABLE PROVEEDOR (
  RUC_PROVEEDOR VARCHAR2(13)   NOT NULL,
  NOMBRE        VARCHAR2(100)  NOT NULL,
  TELEFONO      VARCHAR2(15),
  EMAIL         VARCHAR2(100),
  DIRECCION     VARCHAR2(150),
  CONSTRAINT PK_PROVEEDOR PRIMARY KEY (RUC_PROVEEDOR)
);

CREATE TABLE PRODUCTO (
  COD_PRODUCTO    NUMBER(6)     NOT NULL,
  NOMBRE          VARCHAR2(100) NOT NULL,
  DESCRIPCION     VARCHAR2(200),
  PRECIO          NUMBER(10,2)  NOT NULL,
  REQUIERE_RECETA CHAR(1)       DEFAULT 'N' NOT NULL,
  COD_CATEGORIA   NUMBER(3)     NOT NULL,
  RUC_PROVEEDOR   VARCHAR2(13)  NOT NULL,
  CONSTRAINT PK_PRODUCTO PRIMARY KEY (COD_PRODUCTO),
  CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA (COD_CATEGORIA),
  CONSTRAINT FK_PRODUCTO_PROVEEDOR FOREIGN KEY (RUC_PROVEEDOR) REFERENCES PROVEEDOR (RUC_PROVEEDOR),
  CONSTRAINT CK_PRODUCTO_RECETA CHECK (REQUIERE_RECETA IN ('S','N'))
);

CREATE TABLE INVENTARIO (
  COD_INVENTARIO NUMBER(10)    NOT NULL,
  COD_PRODUCTO   NUMBER(6)     NOT NULL,
  COD_SUCURSAL   NUMBER(3)     NOT NULL,
  STOCK          NUMBER(8)     DEFAULT 0 NOT NULL,
  STOCK_MIN      NUMBER(8)     DEFAULT 0 NOT NULL,
  STOCK_MAX      NUMBER(8),
  CONSTRAINT PK_INVENTARIO PRIMARY KEY (COD_INVENTARIO),
  CONSTRAINT FK_INVENTARIO_PRODUCTO FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO (COD_PRODUCTO),
  CONSTRAINT FK_INVENTARIO_SUCURSAL FOREIGN KEY (COD_SUCURSAL) REFERENCES SUCURSAL (COD_SUCURSAL),
  CONSTRAINT UQ_INVENTARIO_PROD_SUC UNIQUE (COD_PRODUCTO, COD_SUCURSAL),
  CONSTRAINT CK_INVENTARIO_STOCK CHECK (STOCK >= 0)
);

CREATE SEQUENCE SEQ_SUCURSAL   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORIA  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUCTO   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INVENTARIO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE EMPLEADO (
  CED_EMPLEADO  VARCHAR2(10)  NOT NULL,
  NOMBRES       VARCHAR2(60)  NOT NULL,
  APELLIDOS     VARCHAR2(60)  NOT NULL,
  CARGO         VARCHAR2(40)  NOT NULL,
  TELEFONO      VARCHAR2(15),
  COD_SUCURSAL  NUMBER(3)     NOT NULL,
  CONSTRAINT PK_EMPLEADO PRIMARY KEY (CED_EMPLEADO),
  CONSTRAINT FK_EMPLEADO_SUCURSAL FOREIGN KEY (COD_SUCURSAL) REFERENCES SUCURSAL (COD_SUCURSAL)
);

CREATE TABLE CLIENTE (
  CED_CLIENTE   VARCHAR2(10)  NOT NULL,
  NOMBRES       VARCHAR2(60)  NOT NULL,
  APELLIDOS     VARCHAR2(60)  NOT NULL,
  TELEFONO      VARCHAR2(15),
  EMAIL         VARCHAR2(100),
  DIRECCION     VARCHAR2(150),
  CONSTRAINT PK_CLIENTE PRIMARY KEY (CED_CLIENTE)
);

CREATE TABLE VENTA (
  NUM_VENTA     NUMBER(10)    NOT NULL,
  FECHA         DATE          DEFAULT SYSDATE NOT NULL,
  CED_CLIENTE   VARCHAR2(10),
  CED_EMPLEADO  VARCHAR2(10)  NOT NULL,
  COD_SUCURSAL  NUMBER(3)     NOT NULL,
  CONSTRAINT PK_VENTA PRIMARY KEY (NUM_VENTA),
  CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (CED_CLIENTE) REFERENCES CLIENTE (CED_CLIENTE),
  CONSTRAINT FK_VENTA_EMPLEADO FOREIGN KEY (CED_EMPLEADO) REFERENCES EMPLEADO (CED_EMPLEADO),
  CONSTRAINT FK_VENTA_SUCURSAL FOREIGN KEY (COD_SUCURSAL) REFERENCES SUCURSAL (COD_SUCURSAL)
);

CREATE TABLE DETALLE_VENTA (
  NUM_VENTA      NUMBER(10)    NOT NULL,
  COD_PRODUCTO   NUMBER(6)     NOT NULL,
  CANTIDAD       NUMBER(6)     NOT NULL,
  PRECIO_UNIT    NUMBER(10,2)  NOT NULL,
  CONSTRAINT PK_DETALLE_VENTA PRIMARY KEY (NUM_VENTA, COD_PRODUCTO),
  CONSTRAINT FK_DETVENTA_VENTA FOREIGN KEY (NUM_VENTA) REFERENCES VENTA (NUM_VENTA),
  CONSTRAINT FK_DETVENTA_PRODUCTO FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO (COD_PRODUCTO),
  CONSTRAINT CK_DETVENTA_CANTIDAD CHECK (CANTIDAD > 0),
  CONSTRAINT CK_DETVENTA_PRECIO CHECK (PRECIO_UNIT >= 0)
);

CREATE SEQUENCE SEQ_VENTA START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE COMPRA (
  NUM_COMPRA    NUMBER(10)    NOT NULL,
  FECHA         DATE          DEFAULT SYSDATE NOT NULL,
  ESTADO        VARCHAR2(15)  DEFAULT 'PENDIENTE' NOT NULL,
  RUC_PROVEEDOR VARCHAR2(13)  NOT NULL,
  COD_SUCURSAL  NUMBER(3)     NOT NULL,
  CONSTRAINT PK_COMPRA PRIMARY KEY (NUM_COMPRA),
  CONSTRAINT FK_COMPRA_PROVEEDOR FOREIGN KEY (RUC_PROVEEDOR) REFERENCES PROVEEDOR (RUC_PROVEEDOR),
  CONSTRAINT FK_COMPRA_SUCURSAL FOREIGN KEY (COD_SUCURSAL) REFERENCES SUCURSAL (COD_SUCURSAL),
  CONSTRAINT CK_COMPRA_ESTADO CHECK (ESTADO IN ('PENDIENTE','RECIBIDA','ANULADA'))
);

CREATE TABLE DETALLE_COMPRA (
  NUM_COMPRA     NUMBER(10)    NOT NULL,
  COD_PRODUCTO   NUMBER(6)     NOT NULL,
  CANTIDAD       NUMBER(6)     NOT NULL,
  PRECIO_COMPRA  NUMBER(10,2)  NOT NULL,
  CONSTRAINT PK_DETALLE_COMPRA PRIMARY KEY (NUM_COMPRA, COD_PRODUCTO),
  CONSTRAINT FK_DETCOMPRA_COMPRA FOREIGN KEY (NUM_COMPRA) REFERENCES COMPRA (NUM_COMPRA),
  CONSTRAINT FK_DETCOMPRA_PRODUCTO FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO (COD_PRODUCTO),
  CONSTRAINT CK_DETCOMPRA_CANTIDAD CHECK (CANTIDAD > 0),
  CONSTRAINT CK_DETCOMPRA_PRECIO CHECK (PRECIO_COMPRA >= 0)
);

CREATE SEQUENCE SEQ_COMPRA START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- INDICES
-- ============================================================

-- IX_PRODUCTO_CATEGORIA: acelera el JOIN PRODUCTO-CATEGORIA y la validacion
-- de la FK al insertar o actualizar productos.
CREATE INDEX IX_PRODUCTO_CATEGORIA ON PRODUCTO (COD_CATEGORIA);

-- IX_PRODUCTO_PROVEEDOR: acelera el JOIN PRODUCTO-PROVEEDOR y las consultas
-- de "productos por proveedor" para planificar compras.
CREATE INDEX IX_PRODUCTO_PROVEEDOR ON PRODUCTO (RUC_PROVEEDOR);

-- IX_INVENTARIO_PRODUCTO: acelera las consultas de stock por producto y la
-- validacion de la FK de COD_PRODUCTO.
CREATE INDEX IX_INVENTARIO_PRODUCTO ON INVENTARIO (COD_PRODUCTO);

-- IX_INVENTARIO_SUCURSAL: acelera el reporte de inventario por sucursal y la
-- validacion de la FK de COD_SUCURSAL.
CREATE INDEX IX_INVENTARIO_SUCURSAL ON INVENTARIO (COD_SUCURSAL);

-- IX_EMPLEADO_SUCURSAL: acelera listar empleados por sucursal y la FK.
CREATE INDEX IX_EMPLEADO_SUCURSAL ON EMPLEADO (COD_SUCURSAL);

-- IX_VENTA_CLIENTE: acelera el historial de compras por cliente y la FK.
CREATE INDEX IX_VENTA_CLIENTE ON VENTA (CED_CLIENTE);

-- IX_VENTA_EMPLEADO: acelera las ventas por vendedor y la FK.
CREATE INDEX IX_VENTA_EMPLEADO ON VENTA (CED_EMPLEADO);

-- IX_VENTA_SUC_FECHA: indice COMPUESTO. Acelera el reporte de ventas por
-- sucursal y rango de fechas (RF-12) y ademas cubre la FK de COD_SUCURSAL,
-- por lo que no se crea un indice simple aparte para esa FK.
CREATE INDEX IX_VENTA_SUC_FECHA ON VENTA (COD_SUCURSAL, FECHA);

-- IX_DETVENTA_PRODUCTO: acelera la FK y el reporte de productos mas vendidos.
-- (NUM_VENTA ya esta indexado por la PK compuesta, no se duplica.)
CREATE INDEX IX_DETVENTA_PRODUCTO ON DETALLE_VENTA (COD_PRODUCTO);

-- IX_COMPRA_PROVEEDOR: acelera las compras por proveedor y la FK.
CREATE INDEX IX_COMPRA_PROVEEDOR ON COMPRA (RUC_PROVEEDOR);

-- IX_COMPRA_SUCURSAL: acelera las compras por sucursal y la FK.
CREATE INDEX IX_COMPRA_SUCURSAL ON COMPRA (COD_SUCURSAL);

-- IX_DETCOMPRA_PRODUCTO: acelera la FK y el analisis de costo por producto.
-- (NUM_COMPRA ya esta indexado por la PK compuesta, no se duplica.)
CREATE INDEX IX_DETCOMPRA_PRODUCTO ON DETALLE_COMPRA (COD_PRODUCTO);

-- IX_PRODUCTO_NOMBRE: indice SIMPLE. Acelera la busqueda de productos por
-- nombre en el punto de venta (cajero en hora pico).
CREATE INDEX IX_PRODUCTO_NOMBRE ON PRODUCTO (NOMBRE);


INSERT INTO SUCURSAL (COD_SUCURSAL, NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES (1, 'Sucursal Macas', 'Macas', 'Av. 9 de Octubre y Tarqui', '073000111');
INSERT INTO SUCURSAL (COD_SUCURSAL, NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES (2, 'Sucursal SucÃºa', 'SucÃºa', 'Av. Amazonas y 29 de Febrero', '073000222');
INSERT INTO SUCURSAL (COD_SUCURSAL, NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES (3, 'Sucursal MÃ©ndez', 'MÃ©ndez', 'Calle Santiago y Sucre', '073000333');
INSERT INTO SUCURSAL (COD_SUCURSAL, NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES (4, 'Sucursal Zamora', 'Zamora', 'Av. del EjÃ©rcito y Sevilla de Oro', '073000444');
INSERT INTO SUCURSAL (COD_SUCURSAL, NOMBRE, CIUDAD, DIRECCION, TELEFONO) VALUES (5, 'Sucursal Gualaquiza', 'Gualaquiza', 'Av. Quito y 6 de Diciembre', '073000555');

INSERT INTO CATEGORIA (COD_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (1, 'AnalgÃ©sicos', 'Medicamentos para el dolor y la fiebre');
INSERT INTO CATEGORIA (COD_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (2, 'AntibiÃ³ticos', 'Medicamentos contra infecciones bacterianas');
INSERT INTO CATEGORIA (COD_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (3, 'Cuidado Personal', 'Productos de higiene personal');
INSERT INTO CATEGORIA (COD_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (4, 'Belleza', 'CosmÃ©ticos y cremas');
INSERT INTO CATEGORIA (COD_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (5, 'Vitaminas', 'Suplementos alimenticios');

INSERT INTO PROVEEDOR (RUC_PROVEEDOR, NOMBRE, TELEFONO, EMAIL, DIRECCION) VALUES ('1790012345001', 'FarmacÃ©utica del Austro S.A.', '072345678', 'ventas@farmaceuticaaustro.ec', 'Cuenca, Av. Las AmÃ©ricas');
INSERT INTO PROVEEDOR (RUC_PROVEEDOR, NOMBRE, TELEFONO, EMAIL, DIRECCION) VALUES ('1790012345002', 'DroguerÃ­a Nacional CÃ­a. Ltda.', '022987654', 'compras@droguerianacional.ec', 'Quito, Av. Eloy Alfaro');
INSERT INTO PROVEEDOR (RUC_PROVEEDOR, NOMBRE, TELEFONO, EMAIL, DIRECCION) VALUES ('1790012345003', 'Distribuidora Vida Sana', '042345678', 'info@vidasana.ec', 'Guayaquil, Km 5 VÃ­a Daule');
INSERT INTO PROVEEDOR (RUC_PROVEEDOR, NOMBRE, TELEFONO, EMAIL, DIRECCION) VALUES ('1790012345004', 'Laboratorios Andinos', '072233445', 'contacto@labandinos.ec', 'Loja, Av. Universitaria');
INSERT INTO PROVEEDOR (RUC_PROVEEDOR, NOMBRE, TELEFONO, EMAIL, DIRECCION) VALUES ('1790012345005', 'Comercial Belleza EC', '0987654321', 'ventas@bellezaec.com', 'Ambato, Av. Cevallos');

INSERT INTO PRODUCTO (COD_PRODUCTO, NOMBRE, DESCRIPCION, PRECIO, REQUIERE_RECETA, COD_CATEGORIA, RUC_PROVEEDOR) VALUES (1, 'Paracetamol 500mg', 'AnalgÃ©sico en tabletas x 20', 1.50, 'N', 1, '1790012345001');
INSERT INTO PRODUCTO (COD_PRODUCTO, NOMBRE, DESCRIPCION, PRECIO, REQUIERE_RECETA, COD_CATEGORIA, RUC_PROVEEDOR) VALUES (2, 'Amoxicilina 500mg', 'AntibiÃ³tico en cÃ¡psulas x 12', 3.75, 'S', 2, '1790012345002');
INSERT INTO PRODUCTO (COD_PRODUCTO, NOMBRE, DESCRIPCION, PRECIO, REQUIERE_RECETA, COD_CATEGORIA, RUC_PROVEEDOR) VALUES (3, 'Shampoo Anticaspa', 'Shampoo de 400ml', 5.20, 'N', 3, '1790012345005');
INSERT INTO PRODUCTO (COD_PRODUCTO, NOMBRE, DESCRIPCION, PRECIO, REQUIERE_RECETA, COD_CATEGORIA, RUC_PROVEEDOR) VALUES (4, 'Crema Facial Hidratante', 'Crema humectante 50g', 8.90, 'N', 4, '1790012345005');
INSERT INTO PRODUCTO (COD_PRODUCTO, NOMBRE, DESCRIPCION, PRECIO, REQUIERE_RECETA, COD_CATEGORIA, RUC_PROVEEDOR) VALUES (5, 'Vitamina C 1g', 'Tabletas efervescentes x 10', 4.30, 'N', 5, '1790012345004');

INSERT INTO INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (1, 1, 1, 50, 10, 200);
INSERT INTO INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (2, 2, 1, 8, 10, 150);
INSERT INTO INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (3, 3, 2, 30, 15, 100);
INSERT INTO INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (4, 4, 2, 0, 5, 80);
INSERT INTO INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (5, 5, 3, 25, 10, 120);

INSERT INTO EMPLEADO (CED_EMPLEADO, NOMBRES, APELLIDOS, CARGO, TELEFONO, COD_SUCURSAL) VALUES ('1400112233', 'Ana', 'PÃ©rez', 'Cajera', '0991112233', 1);
INSERT INTO EMPLEADO (CED_EMPLEADO, NOMBRES, APELLIDOS, CARGO, TELEFONO, COD_SUCURSAL) VALUES ('1400112244', 'Luis', 'GÃ³mez', 'Jefe de Inventario', '0992223344', 1);
INSERT INTO EMPLEADO (CED_EMPLEADO, NOMBRES, APELLIDOS, CARGO, TELEFONO, COD_SUCURSAL) VALUES ('1400112255', 'MarÃ­a', 'Sarmiento', 'Cajera', '0993334455', 2);
INSERT INTO EMPLEADO (CED_EMPLEADO, NOMBRES, APELLIDOS, CARGO, TELEFONO, COD_SUCURSAL) VALUES ('1400112266', 'Carlos', 'Vega', 'Administrador', '0994445566', 3);
INSERT INTO EMPLEADO (CED_EMPLEADO, NOMBRES, APELLIDOS, CARGO, TELEFONO, COD_SUCURSAL) VALUES ('1400112277', 'Rosa', 'Quituisaca', 'Jefe de Inventario', '0995556677', 4);

INSERT INTO CLIENTE (CED_CLIENTE, NOMBRES, APELLIDOS, TELEFONO, EMAIL, DIRECCION) VALUES ('0102030405', 'Juan', 'Mora', '0981111222', 'juan.mora@mail.com', 'Macas, Barrio Central');
INSERT INTO CLIENTE (CED_CLIENTE, NOMBRES, APELLIDOS, TELEFONO, EMAIL, DIRECCION) VALUES ('0102030406', 'Karen', 'Shiguango', '0982222333', 'karen.s@mail.com', 'SucÃºa, Av. Amazonas');
INSERT INTO CLIENTE (CED_CLIENTE, NOMBRES, APELLIDOS, TELEFONO, EMAIL, DIRECCION) VALUES ('0102030407', 'Pedro', 'Aguinda', '0983333444', 'pedro.ag@mail.com', 'Zamora, Barrio El Dorado');
INSERT INTO CLIENTE (CED_CLIENTE, NOMBRES, APELLIDOS, TELEFONO, EMAIL, DIRECCION) VALUES ('0102030408', 'LucÃ­a', 'Tapia', '0984444555', 'lucia.t@mail.com', 'MÃ©ndez, Calle Sucre');
INSERT INTO CLIENTE (CED_CLIENTE, NOMBRES, APELLIDOS, TELEFONO, EMAIL, DIRECCION) VALUES ('0102030409', 'Diego', 'Cabrera', '0985555666', 'diego.c@mail.com', 'Gualaquiza, Av. Quito');

INSERT INTO VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (1, DATE '2026-09-01', '0102030405', '1400112233', 1);
INSERT INTO VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (2, DATE '2026-09-02', '0102030406', '1400112255', 2);
INSERT INTO VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (3, DATE '2026-09-03', NULL, '1400112233', 1);
INSERT INTO VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (4, DATE '2026-09-04', '0102030407', '1400112266', 3);
INSERT INTO VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (5, DATE '2026-09-05', '0102030408', '1400112277', 4);

INSERT INTO DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (1, 1, 2, 1.50);
INSERT INTO DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (1, 3, 1, 5.20);
INSERT INTO DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (2, 2, 1, 3.75);
INSERT INTO DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (3, 5, 2, 4.30);
INSERT INTO DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (4, 4, 1, 8.90);

INSERT INTO COMPRA (NUM_COMPRA, FECHA, ESTADO, RUC_PROVEEDOR, COD_SUCURSAL) VALUES (1, DATE '2026-09-01', 'RECIBIDA', '1790012345001', 1);
INSERT INTO COMPRA (NUM_COMPRA, FECHA, ESTADO, RUC_PROVEEDOR, COD_SUCURSAL) VALUES (2, DATE '2026-09-02', 'PENDIENTE', '1790012345002', 1);
INSERT INTO COMPRA (NUM_COMPRA, FECHA, ESTADO, RUC_PROVEEDOR, COD_SUCURSAL) VALUES (3, DATE '2026-09-03', 'RECIBIDA', '1790012345004', 2);
INSERT INTO COMPRA (NUM_COMPRA, FECHA, ESTADO, RUC_PROVEEDOR, COD_SUCURSAL) VALUES (4, DATE '2026-09-04', 'PENDIENTE', '1790012345005', 3);
INSERT INTO COMPRA (NUM_COMPRA, FECHA, ESTADO, RUC_PROVEEDOR, COD_SUCURSAL) VALUES (5, DATE '2026-09-05', 'ANULADA', '1790012345003', 4);

INSERT INTO DETALLE_COMPRA (NUM_COMPRA, COD_PRODUCTO, CANTIDAD, PRECIO_COMPRA) VALUES (1, 1, 100, 1.10);
INSERT INTO DETALLE_COMPRA (NUM_COMPRA, COD_PRODUCTO, CANTIDAD, PRECIO_COMPRA) VALUES (2, 2, 50, 3.00);
INSERT INTO DETALLE_COMPRA (NUM_COMPRA, COD_PRODUCTO, CANTIDAD, PRECIO_COMPRA) VALUES (3, 5, 80, 3.50);
INSERT INTO DETALLE_COMPRA (NUM_COMPRA, COD_PRODUCTO, CANTIDAD, PRECIO_COMPRA) VALUES (4, 3, 60, 4.00);
INSERT INTO DETALLE_COMPRA (NUM_COMPRA, COD_PRODUCTO, CANTIDAD, PRECIO_COMPRA) VALUES (5, 4, 40, 6.50);

COMMIT;


CREATE USER farmaciamia_sucursal IDENTIFIED BY suc12mia
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE TO farmaciamia_sucursal;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM,
      CREATE MATERIALIZED VIEW TO farmaciamia_sucursal;
GRANT UNLIMITED TABLESPACE TO farmaciamia_sucursal;

CREATE TABLE farmaciamia_sucursal.INVENTARIO (
  COD_INVENTARIO NUMBER(10)   NOT NULL,
  COD_PRODUCTO   NUMBER(6)    NOT NULL,
  COD_SUCURSAL   NUMBER(3)    NOT NULL,
  STOCK          NUMBER(8)    DEFAULT 0 NOT NULL,
  STOCK_MIN      NUMBER(8)    DEFAULT 0 NOT NULL,
  STOCK_MAX      NUMBER(8),
  CONSTRAINT PK_SUC_INVENTARIO PRIMARY KEY (COD_INVENTARIO),
  CONSTRAINT UQ_SUC_INV_PROD UNIQUE (COD_PRODUCTO, COD_SUCURSAL),
  CONSTRAINT CK_SUC_INV_STOCK CHECK (STOCK >= 0)
);

CREATE TABLE farmaciamia_sucursal.VENTA (
  NUM_VENTA     NUMBER(10)    NOT NULL,
  FECHA         DATE          DEFAULT SYSDATE NOT NULL,
  CED_CLIENTE   VARCHAR2(10),
  CED_EMPLEADO  VARCHAR2(10)  NOT NULL,
  COD_SUCURSAL  NUMBER(3)     NOT NULL,
  CONSTRAINT PK_SUC_VENTA PRIMARY KEY (NUM_VENTA)
);

CREATE TABLE farmaciamia_sucursal.DETALLE_VENTA (
  NUM_VENTA     NUMBER(10)    NOT NULL,
  COD_PRODUCTO  NUMBER(6)     NOT NULL,
  CANTIDAD      NUMBER(6)     NOT NULL,
  PRECIO_UNIT   NUMBER(10,2)  NOT NULL,
  CONSTRAINT PK_SUC_DETVENTA PRIMARY KEY (NUM_VENTA, COD_PRODUCTO),
  CONSTRAINT FK_SUC_DETVENTA_VENTA FOREIGN KEY (NUM_VENTA) REFERENCES farmaciamia_sucursal.VENTA (NUM_VENTA),
  CONSTRAINT CK_SUC_DETVENTA_CANT CHECK (CANTIDAD > 0)
);

INSERT INTO farmaciamia_sucursal.INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (1, 1, 2, 40, 10, 200);
INSERT INTO farmaciamia_sucursal.INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (2, 2, 2, 15, 10, 150);
INSERT INTO farmaciamia_sucursal.INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (3, 3, 2, 3, 15, 100);
INSERT INTO farmaciamia_sucursal.INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (4, 4, 2, 60, 5, 80);
INSERT INTO farmaciamia_sucursal.INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX) VALUES (5, 5, 2, 20, 10, 120);

INSERT INTO farmaciamia_sucursal.VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (101, DATE '2026-09-06', NULL, '1400112044', 2);
INSERT INTO farmaciamia_sucursal.VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (102, DATE '2026-09-07', NULL, '1400112055', 2);
INSERT INTO farmaciamia_sucursal.VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (103, DATE '2026-09-08', NULL, '1400112044', 2);
INSERT INTO farmaciamia_sucursal.VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (104, DATE '2026-09-09', NULL, '1400112066', 2);
INSERT INTO farmaciamia_sucursal.VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL) VALUES (105, DATE '2026-09-10', NULL, '1400112077', 2);

INSERT INTO farmaciamia_sucursal.DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (101, 1, 3, 1.50);
INSERT INTO farmaciamia_sucursal.DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (102, 2, 2, 3.75);
INSERT INTO farmaciamia_sucursal.DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (103, 3, 1, 5.20);
INSERT INTO farmaciamia_sucursal.DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (104, 4, 2, 8.90);
INSERT INTO farmaciamia_sucursal.DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT) VALUES (105, 5, 4, 4.30);

COMMIT;

GRANT SELECT ON farmaciamia_sucursal.INVENTARIO    TO farmaciamia;
GRANT SELECT ON farmaciamia_sucursal.VENTA         TO farmaciamia;
GRANT SELECT ON farmaciamia_sucursal.DETALLE_VENTA TO farmaciamia;
GRANT SELECT ON farmaciamia.PRODUCTO   TO farmaciamia_sucursal;
GRANT SELECT ON farmaciamia.SUCURSAL   TO farmaciamia_sucursal;
GRANT SELECT ON farmaciamia.INVENTARIO TO farmaciamia_sucursal;
GRANT SELECT ON farmaciamia.VENTA      TO farmaciamia_sucursal;

CREATE OR REPLACE VIEW farmaciamia.VW_INVENTARIO_GLOBAL AS
SELECT 'MATRIZ' AS ORIGEN, i.COD_SUCURSAL, p.COD_PRODUCTO, p.NOMBRE AS PRODUCTO,
       i.STOCK, i.STOCK_MIN,
       CASE WHEN i.STOCK <= i.STOCK_MIN THEN 'ALERTA' ELSE 'OK' END AS ESTADO_STOCK
FROM farmaciamia.INVENTARIO i
JOIN farmaciamia.PRODUCTO p ON p.COD_PRODUCTO = i.COD_PRODUCTO
UNION ALL
SELECT 'SUCURSAL', i.COD_SUCURSAL, p.COD_PRODUCTO, p.NOMBRE,
       i.STOCK, i.STOCK_MIN,
       CASE WHEN i.STOCK <= i.STOCK_MIN THEN 'ALERTA' ELSE 'OK' END
FROM farmaciamia_sucursal.INVENTARIO i
JOIN farmaciamia.PRODUCTO p ON p.COD_PRODUCTO = i.COD_PRODUCTO;

CREATE MATERIALIZED VIEW farmaciamia.MV_VENTAS_GLOBALES
  TABLESPACE USERS
  BUILD IMMEDIATE
  REFRESH COMPLETE ON DEMAND
AS
SELECT 'MATRIZ' AS ORIGEN, v.NUM_VENTA, v.FECHA, v.COD_SUCURSAL,
       d.COD_PRODUCTO, d.CANTIDAD, d.PRECIO_UNIT,
       d.CANTIDAD * d.PRECIO_UNIT AS SUBTOTAL
FROM farmaciamia.VENTA v
JOIN farmaciamia.DETALLE_VENTA d ON d.NUM_VENTA = v.NUM_VENTA
UNION ALL
SELECT 'SUCURSAL', v.NUM_VENTA, v.FECHA, v.COD_SUCURSAL,
       d.COD_PRODUCTO, d.CANTIDAD, d.PRECIO_UNIT,
       d.CANTIDAD * d.PRECIO_UNIT
FROM farmaciamia_sucursal.VENTA v
JOIN farmaciamia_sucursal.DETALLE_VENTA d ON d.NUM_VENTA = v.NUM_VENTA;

BEGIN
  DBMS_SCHEDULER.CREATE_JOB (
    job_name        => 'JOB_MV_VENTAS_DIARIO',
    job_type        => 'PLSQL_BLOCK',
    job_action      => 'BEGIN DBMS_MVIEW.REFRESH(''FARMACIAMIA.MV_VENTAS_GLOBALES'', ''C''); END;',
    start_date      => TRUNC(SYSDATE) + 1 + 1/24,
    repeat_interval => 'FREQ=DAILY;BYHOUR=1;BYMINUTE=0;BYSECOND=0',
    enabled         => TRUE);
END;
/

CREATE OR REPLACE PROCEDURE farmaciamia.PR_VENTA_PRODUCTO (
  p_cod_producto IN NUMBER,
  p_cod_sucursal IN NUMBER,
  p_cantidad     IN NUMBER,
  p_ced_empleado IN VARCHAR2,
  p_ced_cliente  IN VARCHAR2 DEFAULT NULL
) AS
  v_precio NUMBER(10,2);
  v_stock  NUMBER(8);
  v_venta  NUMBER(10);
BEGIN
  SELECT PRECIO INTO v_precio
    FROM farmaciamia.PRODUCTO
   WHERE COD_PRODUCTO = p_cod_producto;
  SELECT STOCK INTO v_stock
    FROM farmaciamia.INVENTARIO
   WHERE COD_PRODUCTO = p_cod_producto AND COD_SUCURSAL = p_cod_sucursal;
  IF v_stock < p_cantidad THEN
    RAISE_APPLICATION_ERROR(-20001, 'Stock insuficiente para el producto ' || p_cod_producto);
  END IF;
  SELECT NVL(MAX(NUM_VENTA), 0) + 1 INTO v_venta FROM farmaciamia.VENTA;
  INSERT INTO farmaciamia.VENTA (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL)
  VALUES (v_venta, SYSDATE, p_ced_cliente, p_ced_empleado, p_cod_sucursal);
  INSERT INTO farmaciamia.DETALLE_VENTA (NUM_VENTA, COD_PRODUCTO, CANTIDAD, PRECIO_UNIT)
  VALUES (v_venta, p_cod_producto, p_cantidad, v_precio);
  UPDATE farmaciamia.INVENTARIO
     SET STOCK = STOCK - p_cantidad
   WHERE COD_PRODUCTO = p_cod_producto AND COD_SUCURSAL = p_cod_sucursal;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Venta ' || v_venta || ' registrada. Stock restante: ' || (v_stock - p_cantidad));
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20002, 'Producto o inventario no encontrado');
END;
/

CREATE OR REPLACE PROCEDURE farmaciamia.PR_ACTUALIZAR_STOCK (
  p_cod_producto IN NUMBER,
  p_cod_sucursal IN NUMBER,
  p_nuevo_stock  IN NUMBER
) AS
  v_id NUMBER(10);
BEGIN
  IF p_nuevo_stock < 0 THEN
    RAISE_APPLICATION_ERROR(-20003, 'El stock no puede ser negativo');
  END IF;
  UPDATE farmaciamia.INVENTARIO
     SET STOCK = p_nuevo_stock
   WHERE COD_PRODUCTO = p_cod_producto AND COD_SUCURSAL = p_cod_sucursal;
  IF SQL%ROWCOUNT = 0 THEN
    SELECT NVL(MAX(COD_INVENTARIO), 0) + 1 INTO v_id FROM farmaciamia.INVENTARIO;
    INSERT INTO farmaciamia.INVENTARIO (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN)
    VALUES (v_id, p_cod_producto, p_cod_sucursal, p_nuevo_stock, 0);
  END IF;
  COMMIT;
END;
/

CREATE OR REPLACE FUNCTION farmaciamia.FN_TOTAL_VENTA (p_num_venta IN NUMBER)
RETURN NUMBER AS
  v_total NUMBER(12,2);
BEGIN
  SELECT NVL(SUM(CANTIDAD * PRECIO_UNIT), 0) INTO v_total
    FROM farmaciamia.DETALLE_VENTA
   WHERE NUM_VENTA = p_num_venta;
  RETURN v_total;
END;
/

CREATE OR REPLACE FUNCTION farmaciamia.FN_STOCK_GLOBAL (p_cod_producto IN NUMBER)
RETURN NUMBER AS
  v_total NUMBER(10);
BEGIN
  SELECT (SELECT NVL(SUM(STOCK), 0) FROM farmaciamia.INVENTARIO WHERE COD_PRODUCTO = p_cod_producto)
       + (SELECT NVL(SUM(STOCK), 0) FROM farmaciamia_sucursal.INVENTARIO WHERE COD_PRODUCTO = p_cod_producto)
    INTO v_total
    FROM DUAL;
  RETURN v_total;
END;
/

SELECT * FROM farmaciamia.VW_INVENTARIO_GLOBAL;
SELECT * FROM farmaciamia.MV_VENTAS_GLOBALES;
SELECT farmaciamia.FN_TOTAL_VENTA(1) AS TOTAL_VENTA_1 FROM DUAL;
SELECT farmaciamia.FN_STOCK_GLOBAL(1) AS STOCK_GLOBAL_PROD_1 FROM DUAL;


GRANT SELECT ON farmaciamia_sucursal.INVENTARIO    TO farmaciamia;
GRANT SELECT ON farmaciamia_sucursal.VENTA         TO farmaciamia;
GRANT SELECT ON farmaciamia_sucursal.DETALLE_VENTA TO farmaciamia;
GRANT SELECT ON SYS.V_$SESSION     TO farmaciamia;
GRANT SELECT ON SYS.DBA_DATA_FILES TO farmaciamia;
GRANT SELECT ON SYS.DBA_FREE_SPACE TO farmaciamia;


CREATE USER farmaciamia_replica IDENTIFIED BY rep12mia
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE TO farmaciamia_replica;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO farmaciamia_replica;
GRANT UNLIMITED TABLESPACE TO farmaciamia_replica;

CREATE TABLE farmaciamia_replica.PRODUCTO (
  COD_PRODUCTO     NUMBER(6)     NOT NULL,
  NOMBRE           VARCHAR2(100) NOT NULL,
  DESCRIPCION      VARCHAR2(200),
  PRECIO           NUMBER(10,2)  NOT NULL,
  REQUIERE_RECETA  CHAR(1)       NOT NULL,
  COD_CATEGORIA    NUMBER(3)     NOT NULL,
  RUC_PROVEEDOR    VARCHAR2(13)  NOT NULL,
  USUARIO_INSERTO  VARCHAR2(30),
  FECHA_INSERTO    DATE,
  USUARIO_ACTUALIZO VARCHAR2(30),
  FECHA_ACTUALIZO  DATE,
  CONSTRAINT PK_REP_PRODUCTO PRIMARY KEY (COD_PRODUCTO)
);

CREATE TABLE farmaciamia_replica.INVENTARIO (
  COD_INVENTARIO   NUMBER(10)    NOT NULL,
  COD_PRODUCTO     NUMBER(6)     NOT NULL,
  COD_SUCURSAL     NUMBER(3)     NOT NULL,
  STOCK            NUMBER(8)     NOT NULL,
  STOCK_MIN        NUMBER(8)     NOT NULL,
  STOCK_MAX        NUMBER(8),
  USUARIO_INSERTO  VARCHAR2(30),
  FECHA_INSERTO    DATE,
  USUARIO_ACTUALIZO VARCHAR2(30),
  FECHA_ACTUALIZO  DATE,
  CONSTRAINT PK_REP_INVENTARIO PRIMARY KEY (COD_INVENTARIO)
);

CREATE TABLE farmaciamia_replica.VENTA (
  NUM_VENTA        NUMBER(10)    NOT NULL,
  FECHA            DATE          NOT NULL,
  CED_CLIENTE      VARCHAR2(10),
  CED_EMPLEADO     VARCHAR2(10)  NOT NULL,
  COD_SUCURSAL     NUMBER(3)     NOT NULL,
  USUARIO_INSERTO  VARCHAR2(30),
  FECHA_INSERTO    DATE,
  USUARIO_ACTUALIZO VARCHAR2(30),
  FECHA_ACTUALIZO  DATE,
  CONSTRAINT PK_REP_VENTA PRIMARY KEY (NUM_VENTA)
);

CREATE TABLE farmaciamia_replica.REPLICA_EVENTOS (
  ID_EVENTO     NUMBER(12)   NOT NULL,
  TABLA         VARCHAR2(30) NOT NULL,
  OPERACION     VARCHAR2(10) NOT NULL,
  REGISTRO_ID   VARCHAR2(30),
  USUARIO_BD    VARCHAR2(30),
  FECHA_EVENTO  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_REPLICA_EVENTOS PRIMARY KEY (ID_EVENTO),
  CONSTRAINT CK_REPLICA_OP CHECK (OPERACION IN ('INSERT','UPDATE','DELETE'))
);

CREATE SEQUENCE farmaciamia_replica.SEQ_REPLICA_EVENTOS START WITH 1 INCREMENT BY 1 NOCACHE;

GRANT SELECT, INSERT, UPDATE, DELETE ON farmaciamia_replica.PRODUCTO       TO farmaciamia;
GRANT SELECT, INSERT, UPDATE, DELETE ON farmaciamia_replica.INVENTARIO     TO farmaciamia;
GRANT SELECT, INSERT, UPDATE, DELETE ON farmaciamia_replica.VENTA          TO farmaciamia;
GRANT SELECT, INSERT ON farmaciamia_replica.REPLICA_EVENTOS                TO farmaciamia;
GRANT SELECT ON farmaciamia_replica.SEQ_REPLICA_EVENTOS                    TO farmaciamia;

ALTER TABLE farmaciamia.PRODUCTO   ADD (USUARIO_INSERTO VARCHAR2(30), FECHA_INSERTO DATE, USUARIO_ACTUALIZO VARCHAR2(30), FECHA_ACTUALIZO DATE);
ALTER TABLE farmaciamia.INVENTARIO ADD (USUARIO_INSERTO VARCHAR2(30), FECHA_INSERTO DATE, USUARIO_ACTUALIZO VARCHAR2(30), FECHA_ACTUALIZO DATE);
ALTER TABLE farmaciamia.VENTA      ADD (USUARIO_INSERTO VARCHAR2(30), FECHA_INSERTO DATE, USUARIO_ACTUALIZO VARCHAR2(30), FECHA_ACTUALIZO DATE);
ALTER TABLE farmaciamia.CLIENTE    ADD (USUARIO_INSERTO VARCHAR2(30), FECHA_INSERTO DATE, USUARIO_ACTUALIZO VARCHAR2(30), FECHA_ACTUALIZO DATE);

UPDATE farmaciamia.PRODUCTO   SET USUARIO_INSERTO = USER, FECHA_INSERTO = SYSDATE WHERE USUARIO_INSERTO IS NULL;
UPDATE farmaciamia.INVENTARIO SET USUARIO_INSERTO = USER, FECHA_INSERTO = SYSDATE WHERE USUARIO_INSERTO IS NULL;
UPDATE farmaciamia.VENTA      SET USUARIO_INSERTO = USER, FECHA_INSERTO = SYSDATE WHERE USUARIO_INSERTO IS NULL;
UPDATE farmaciamia.CLIENTE    SET USUARIO_INSERTO = USER, FECHA_INSERTO = SYSDATE WHERE USUARIO_INSERTO IS NULL;
COMMIT;

CREATE OR REPLACE TRIGGER farmaciamia.TRG_AUD_PRODUCTO
BEFORE INSERT OR UPDATE ON farmaciamia.PRODUCTO
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.USUARIO_INSERTO := USER;
    :NEW.FECHA_INSERTO   := SYSDATE;
  ELSE
    :NEW.USUARIO_ACTUALIZO := USER;
    :NEW.FECHA_ACTUALIZO   := SYSDATE;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER farmaciamia.TRG_AUD_INVENTARIO
BEFORE INSERT OR UPDATE ON farmaciamia.INVENTARIO
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.USUARIO_INSERTO := USER;
    :NEW.FECHA_INSERTO   := SYSDATE;
  ELSE
    :NEW.USUARIO_ACTUALIZO := USER;
    :NEW.FECHA_ACTUALIZO   := SYSDATE;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER farmaciamia.TRG_AUD_VENTA
BEFORE INSERT OR UPDATE ON farmaciamia.VENTA
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.USUARIO_INSERTO := USER;
    :NEW.FECHA_INSERTO   := SYSDATE;
  ELSE
    :NEW.USUARIO_ACTUALIZO := USER;
    :NEW.FECHA_ACTUALIZO   := SYSDATE;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER farmaciamia.TRG_AUD_CLIENTE
BEFORE INSERT OR UPDATE ON farmaciamia.CLIENTE
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :NEW.USUARIO_INSERTO := USER;
    :NEW.FECHA_INSERTO   := SYSDATE;
  ELSE
    :NEW.USUARIO_ACTUALIZO := USER;
    :NEW.FECHA_ACTUALIZO   := SYSDATE;
  END IF;
END;
/

INSERT INTO farmaciamia_replica.PRODUCTO
  (COD_PRODUCTO, NOMBRE, DESCRIPCION, PRECIO, REQUIERE_RECETA, COD_CATEGORIA, RUC_PROVEEDOR, USUARIO_INSERTO, FECHA_INSERTO, USUARIO_ACTUALIZO, FECHA_ACTUALIZO)
SELECT COD_PRODUCTO, NOMBRE, DESCRIPCION, PRECIO, REQUIERE_RECETA, COD_CATEGORIA, RUC_PROVEEDOR, USUARIO_INSERTO, FECHA_INSERTO, USUARIO_ACTUALIZO, FECHA_ACTUALIZO
FROM farmaciamia.PRODUCTO;

INSERT INTO farmaciamia_replica.INVENTARIO
  (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX, USUARIO_INSERTO, FECHA_INSERTO, USUARIO_ACTUALIZO, FECHA_ACTUALIZO)
SELECT COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX, USUARIO_INSERTO, FECHA_INSERTO, USUARIO_ACTUALIZO, FECHA_ACTUALIZO
FROM farmaciamia.INVENTARIO;

INSERT INTO farmaciamia_replica.VENTA
  (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL, USUARIO_INSERTO, FECHA_INSERTO, USUARIO_ACTUALIZO, FECHA_ACTUALIZO)
SELECT NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL, USUARIO_INSERTO, FECHA_INSERTO, USUARIO_ACTUALIZO, FECHA_ACTUALIZO
FROM farmaciamia.VENTA;
COMMIT;

CREATE OR REPLACE TRIGGER farmaciamia.TRG_REP_PRODUCTO_AI
AFTER INSERT ON farmaciamia.PRODUCTO FOR EACH ROW
BEGIN
  INSERT INTO farmaciamia_replica.PRODUCTO
    (COD_PRODUCTO, NOMBRE, DESCRIPCION, PRECIO, REQUIERE_RECETA, COD_CATEGORIA, RUC_PROVEEDOR, USUARIO_INSERTO, FECHA_INSERTO, USUARIO_ACTUALIZO, FECHA_ACTUALIZO)
  VALUES
    (:NEW.COD_PRODUCTO, :NEW.NOMBRE, :NEW.DESCRIPCION, :NEW.PRECIO, :NEW.REQUIERE_RECETA, :NEW.COD_CATEGORIA, :NEW.RUC_PROVEEDOR, :NEW.USUARIO_INSERTO, :NEW.FECHA_INSERTO, :NEW.USUARIO_ACTUALIZO, :NEW.FECHA_ACTUALIZO);
  INSERT INTO farmaciamia_replica.REPLICA_EVENTOS (ID_EVENTO, TABLA, OPERACION, REGISTRO_ID, USUARIO_BD, FECHA_EVENTO)
  VALUES (farmaciamia_replica.SEQ_REPLICA_EVENTOS.NEXTVAL, 'PRODUCTO', 'INSERT', TO_CHAR(:NEW.COD_PRODUCTO), USER, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER farmaciamia.TRG_REP_PRODUCTO_AU
AFTER UPDATE ON farmaciamia.PRODUCTO FOR EACH ROW
BEGIN
  UPDATE farmaciamia_replica.PRODUCTO
     SET NOMBRE = :NEW.NOMBRE, DESCRIPCION = :NEW.DESCRIPCION, PRECIO = :NEW.PRECIO,
         REQUIERE_RECETA = :NEW.REQUIERE_RECETA, COD_CATEGORIA = :NEW.COD_CATEGORIA, RUC_PROVEEDOR = :NEW.RUC_PROVEEDOR,
         USUARIO_ACTUALIZO = :NEW.USUARIO_ACTUALIZO, FECHA_ACTUALIZO = :NEW.FECHA_ACTUALIZO
   WHERE COD_PRODUCTO = :OLD.COD_PRODUCTO;
  INSERT INTO farmaciamia_replica.REPLICA_EVENTOS (ID_EVENTO, TABLA, OPERACION, REGISTRO_ID, USUARIO_BD, FECHA_EVENTO)
  VALUES (farmaciamia_replica.SEQ_REPLICA_EVENTOS.NEXTVAL, 'PRODUCTO', 'UPDATE', TO_CHAR(:NEW.COD_PRODUCTO), USER, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER farmaciamia.TRG_REP_PRODUCTO_AD
AFTER DELETE ON farmaciamia.PRODUCTO FOR EACH ROW
BEGIN
  DELETE FROM farmaciamia_replica.PRODUCTO WHERE COD_PRODUCTO = :OLD.COD_PRODUCTO;
  INSERT INTO farmaciamia_replica.REPLICA_EVENTOS (ID_EVENTO, TABLA, OPERACION, REGISTRO_ID, USUARIO_BD, FECHA_EVENTO)
  VALUES (farmaciamia_replica.SEQ_REPLICA_EVENTOS.NEXTVAL, 'PRODUCTO', 'DELETE', TO_CHAR(:OLD.COD_PRODUCTO), USER, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER farmaciamia.TRG_REP_INVENTARIO_AI
AFTER INSERT ON farmaciamia.INVENTARIO FOR EACH ROW
BEGIN
  INSERT INTO farmaciamia_replica.INVENTARIO
    (COD_INVENTARIO, COD_PRODUCTO, COD_SUCURSAL, STOCK, STOCK_MIN, STOCK_MAX, USUARIO_INSERTO, FECHA_INSERTO, USUARIO_ACTUALIZO, FECHA_ACTUALIZO)
  VALUES
    (:NEW.COD_INVENTARIO, :NEW.COD_PRODUCTO, :NEW.COD_SUCURSAL, :NEW.STOCK, :NEW.STOCK_MIN, :NEW.STOCK_MAX, :NEW.USUARIO_INSERTO, :NEW.FECHA_INSERTO, :NEW.USUARIO_ACTUALIZO, :NEW.FECHA_ACTUALIZO);
  INSERT INTO farmaciamia_replica.REPLICA_EVENTOS (ID_EVENTO, TABLA, OPERACION, REGISTRO_ID, USUARIO_BD, FECHA_EVENTO)
  VALUES (farmaciamia_replica.SEQ_REPLICA_EVENTOS.NEXTVAL, 'INVENTARIO', 'INSERT', TO_CHAR(:NEW.COD_INVENTARIO), USER, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER farmaciamia.TRG_REP_INVENTARIO_AU
AFTER UPDATE ON farmaciamia.INVENTARIO FOR EACH ROW
BEGIN
  UPDATE farmaciamia_replica.INVENTARIO
     SET COD_PRODUCTO = :NEW.COD_PRODUCTO, COD_SUCURSAL = :NEW.COD_SUCURSAL, STOCK = :NEW.STOCK,
         STOCK_MIN = :NEW.STOCK_MIN, STOCK_MAX = :NEW.STOCK_MAX,
         USUARIO_ACTUALIZO = :NEW.USUARIO_ACTUALIZO, FECHA_ACTUALIZO = :NEW.FECHA_ACTUALIZO
   WHERE COD_INVENTARIO = :OLD.COD_INVENTARIO;
  INSERT INTO farmaciamia_replica.REPLICA_EVENTOS (ID_EVENTO, TABLA, OPERACION, REGISTRO_ID, USUARIO_BD, FECHA_EVENTO)
  VALUES (farmaciamia_replica.SEQ_REPLICA_EVENTOS.NEXTVAL, 'INVENTARIO', 'UPDATE', TO_CHAR(:NEW.COD_INVENTARIO), USER, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER farmaciamia.TRG_REP_INVENTARIO_AD
AFTER DELETE ON farmaciamia.INVENTARIO FOR EACH ROW
BEGIN
  DELETE FROM farmaciamia_replica.INVENTARIO WHERE COD_INVENTARIO = :OLD.COD_INVENTARIO;
  INSERT INTO farmaciamia_replica.REPLICA_EVENTOS (ID_EVENTO, TABLA, OPERACION, REGISTRO_ID, USUARIO_BD, FECHA_EVENTO)
  VALUES (farmaciamia_replica.SEQ_REPLICA_EVENTOS.NEXTVAL, 'INVENTARIO', 'DELETE', TO_CHAR(:OLD.COD_INVENTARIO), USER, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER farmaciamia.TRG_REP_VENTA_AI
AFTER INSERT ON farmaciamia.VENTA FOR EACH ROW
BEGIN
  INSERT INTO farmaciamia_replica.VENTA
    (NUM_VENTA, FECHA, CED_CLIENTE, CED_EMPLEADO, COD_SUCURSAL, USUARIO_INSERTO, FECHA_INSERTO, USUARIO_ACTUALIZO, FECHA_ACTUALIZO)
  VALUES
    (:NEW.NUM_VENTA, :NEW.FECHA, :NEW.CED_CLIENTE, :NEW.CED_EMPLEADO, :NEW.COD_SUCURSAL, :NEW.USUARIO_INSERTO, :NEW.FECHA_INSERTO, :NEW.USUARIO_ACTUALIZO, :NEW.FECHA_ACTUALIZO);
  INSERT INTO farmaciamia_replica.REPLICA_EVENTOS (ID_EVENTO, TABLA, OPERACION, REGISTRO_ID, USUARIO_BD, FECHA_EVENTO)
  VALUES (farmaciamia_replica.SEQ_REPLICA_EVENTOS.NEXTVAL, 'VENTA', 'INSERT', TO_CHAR(:NEW.NUM_VENTA), USER, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER farmaciamia.TRG_REP_VENTA_AU
AFTER UPDATE ON farmaciamia.VENTA FOR EACH ROW
BEGIN
  UPDATE farmaciamia_replica.VENTA
     SET FECHA = :NEW.FECHA, CED_CLIENTE = :NEW.CED_CLIENTE, CED_EMPLEADO = :NEW.CED_EMPLEADO,
         COD_SUCURSAL = :NEW.COD_SUCURSAL,
         USUARIO_ACTUALIZO = :NEW.USUARIO_ACTUALIZO, FECHA_ACTUALIZO = :NEW.FECHA_ACTUALIZO
   WHERE NUM_VENTA = :OLD.NUM_VENTA;
  INSERT INTO farmaciamia_replica.REPLICA_EVENTOS (ID_EVENTO, TABLA, OPERACION, REGISTRO_ID, USUARIO_BD, FECHA_EVENTO)
  VALUES (farmaciamia_replica.SEQ_REPLICA_EVENTOS.NEXTVAL, 'VENTA', 'UPDATE', TO_CHAR(:NEW.NUM_VENTA), USER, SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER farmaciamia.TRG_REP_VENTA_AD
AFTER DELETE ON farmaciamia.VENTA FOR EACH ROW
BEGIN
  DELETE FROM farmaciamia_replica.VENTA WHERE NUM_VENTA = :OLD.NUM_VENTA;
  INSERT INTO farmaciamia_replica.REPLICA_EVENTOS (ID_EVENTO, TABLA, OPERACION, REGISTRO_ID, USUARIO_BD, FECHA_EVENTO)
  VALUES (farmaciamia_replica.SEQ_REPLICA_EVENTOS.NEXTVAL, 'VENTA', 'DELETE', TO_CHAR(:OLD.NUM_VENTA), USER, SYSDATE);
END;
/

CREATE ROLE ROL_CONSULTA;
CREATE ROLE ROL_VENTAS;
CREATE ROLE ROL_ALMACEN;

GRANT SELECT ON farmaciamia.SUCURSAL      TO ROL_CONSULTA;
GRANT SELECT ON farmaciamia.CATEGORIA     TO ROL_CONSULTA;
GRANT SELECT ON farmaciamia.PROVEEDOR     TO ROL_CONSULTA;
GRANT SELECT ON farmaciamia.PRODUCTO      TO ROL_CONSULTA;
GRANT SELECT ON farmaciamia.INVENTARIO    TO ROL_CONSULTA;
GRANT SELECT ON farmaciamia.EMPLEADO      TO ROL_CONSULTA;
GRANT SELECT ON farmaciamia.CLIENTE       TO ROL_CONSULTA;
GRANT SELECT ON farmaciamia.VENTA         TO ROL_CONSULTA;
GRANT SELECT ON farmaciamia.DETALLE_VENTA TO ROL_CONSULTA;
GRANT SELECT ON farmaciamia.COMPRA        TO ROL_CONSULTA;
GRANT SELECT ON farmaciamia.DETALLE_COMPRA TO ROL_CONSULTA;

GRANT SELECT ON farmaciamia.SUCURSAL      TO ROL_VENTAS;
GRANT SELECT ON farmaciamia.CATEGORIA     TO ROL_VENTAS;
GRANT SELECT ON farmaciamia.PRODUCTO      TO ROL_VENTAS;
GRANT SELECT ON farmaciamia.INVENTARIO    TO ROL_VENTAS;
GRANT SELECT, INSERT ON farmaciamia.CLIENTE       TO ROL_VENTAS;
GRANT SELECT, INSERT ON farmaciamia.VENTA         TO ROL_VENTAS;
GRANT SELECT, INSERT ON farmaciamia.DETALLE_VENTA TO ROL_VENTAS;

GRANT SELECT ON farmaciamia.SUCURSAL      TO ROL_ALMACEN;
GRANT SELECT ON farmaciamia.CATEGORIA     TO ROL_ALMACEN;
GRANT SELECT ON farmaciamia.PROVEEDOR     TO ROL_ALMACEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON farmaciamia.PRODUCTO      TO ROL_ALMACEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON farmaciamia.INVENTARIO    TO ROL_ALMACEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON farmaciamia.COMPRA        TO ROL_ALMACEN;
GRANT SELECT, INSERT, UPDATE, DELETE ON farmaciamia.DETALLE_COMPRA TO ROL_ALMACEN;

CREATE USER u_consulta IDENTIFIED BY cons12ulta;
CREATE USER u_ventas   IDENTIFIED BY vent12as;
CREATE USER u_almacen  IDENTIFIED BY alm12acen;

GRANT CREATE SESSION TO u_consulta;
GRANT CREATE SESSION TO u_ventas;
GRANT CREATE SESSION TO u_almacen;

GRANT ROL_CONSULTA TO u_consulta;
GRANT ROL_VENTAS   TO u_ventas;
GRANT ROL_ALMACEN  TO u_almacen;

CREATE OR REPLACE VIEW farmaciamia.VW_SESIONES_ACTIVAS AS
SELECT S.SID, S.SERIAL# AS SERIAL, S.USERNAME, S.STATUS, S.MACHINE, S.PROGRAM, S.LOGON_TIME
FROM V$SESSION S
WHERE S.TYPE = 'USER' AND S.USERNAME IS NOT NULL;

CREATE OR REPLACE VIEW farmaciamia.VW_USO_TABLESPACES AS
SELECT D.TABLESPACE_NAME,
       ROUND(D.BYTES / 1024 / 1024, 2) AS TAMANO_MB,
       ROUND(NVL(F.BYTES, 0) / 1024 / 1024, 2) AS LIBRE_MB,
       ROUND((D.BYTES - NVL(F.BYTES, 0)) / 1024 / 1024, 2) AS USADO_MB,
       ROUND((D.BYTES - NVL(F.BYTES, 0)) / D.BYTES * 100, 2) AS PORC_USADO
FROM (SELECT TABLESPACE_NAME, SUM(BYTES) BYTES FROM DBA_DATA_FILES GROUP BY TABLESPACE_NAME) D
LEFT JOIN (SELECT TABLESPACE_NAME, SUM(BYTES) BYTES FROM DBA_FREE_SPACE GROUP BY TABLESPACE_NAME) F
  ON D.TABLESPACE_NAME = F.TABLESPACE_NAME;

INSERT INTO farmaciamia.PRODUCTO (COD_PRODUCTO, NOMBRE, DESCRIPCION, PRECIO, REQUIERE_RECETA, COD_CATEGORIA, RUC_PROVEEDOR)
VALUES (99, 'Producto Prueba Replica', 'Prueba de replicacion', 9.99, 'N', 1, '1790012345001');
UPDATE farmaciamia.PRODUCTO SET PRECIO = 10.50 WHERE COD_PRODUCTO = 99;
DELETE FROM farmaciamia.PRODUCTO WHERE COD_PRODUCTO = 99;
COMMIT;

SELECT * FROM farmaciamia_replica.PRODUCTO WHERE COD_PRODUCTO = 99;
SELECT ID_EVENTO, TABLA, OPERACION, REGISTRO_ID, USUARIO_BD, FECHA_EVENTO FROM farmaciamia_replica.REPLICA_EVENTOS ORDER BY ID_EVENTO;
SELECT * FROM farmaciamia.VW_SESIONES_ACTIVAS;
SELECT * FROM farmaciamia.VW_USO_TABLESPACES;
